### ISSUE TITLE
Last changes in jvmtop.java source code are not included in compiled release

### ISSUE THREAD

**Issue by racagalro** [HubSpot/jvmtop#68]
I've seen inside jvmtop.class source code that parser accepts new command line options  to change or disable limit in the number listed threads.

However, the jvmtop.jar version 0.8.0 doesn't include them. The following error is reported:
$ jvmtop.sh --threadlimit 10  6434
Exception in thread "main" joptsimple.UnrecognizedOptionException: 'threadlimit' is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:89)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:493)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:433)
	at com.jvmtop.JvmTop.main(Unknown Source)

Could you please recompile a new release or give me  instructions to compile it by myself from source?

Thanks.

**Comment by eabbott** [comment]
Hi @racagalro the HubSpot/jvmtop repo was `Automatically exported from code.google.com/p/jvmtop`. Any distributions of the code should come from there I'd think.

If you are interested in building the tool yourself, you can look at the [`hs-master`](https://github.com/HubSpot/jvmtop/blob/hs-master/jvmtop) branch to see how we're building it.
